baseURL: "https://leovan.me/"
languageCode: "en-us"
title: "Leo Van | 范叶亮"
googleAnalytics: "G-RJC7CCKE67"
disqusShortname: "leovan"
ignoreFiles: [
  "\\.Rmarkdown$", "\\.Rmd$", "\\.knit\\.md$", "\\.utf8\\.md$",
  "_files$", "_cache$", "\\.txt$", "\\.csv$", "\\.tsv$",
  "\\.tgz$", "\\.tar$", "\\.gz$", "\\.zip$", "\\.npz$"]
hasCJKLanguage: true
enableEmoji: true
rssLimit: 100

permalinks:
  cn: "/cn/:year/:month/:slug/"
  en: "/en/:year/:month/:slug/"
  tech101: "/tech101/:year/:month/:slug/"

menu:
  home:
    - name: "博客"
      url: "/cn/"
      weight: 1
    - name: "关于"
      url: "/cn/about/"
      weight: 2
    - name: "Blog"
      url: "/en/"
      weight: 3
    - name: "About"
      url: "/en/about/"
      weight: 4
  main:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "博客"
      url: "/cn/"
      weight: 2
    - name: "关于"
      url: "/cn/about/"
      weight: 3
    - identifier: "menu-separator-1"
      url: "#menu-separator"
      weight: 4
    - name: "Home"
      url: "/"
      weight: 5
    - name: "Blog"
      url: "/en/"
      weight: 6
    - name: "About"
      url: "/en/about/"
      weight: 7
  en:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Blog"
      url: "/en/"
      weight: 2
    - name: "Categories"
      url: "/categories/"
      weight: 3
    - identifier: "en-menu-separator-1"
      url: "#menu-separator"
      weight: 4
    - name: "About"
      url: "/en/about/"
      weight: 5
    - name: "Resume"
      url: "/en/resume/"
      weight: 6
  cn:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "博客"
      url: "/cn/"
      weight: 2
    - name: "分类"
      url: "/categories/"
      weight: 3
    - name: "Tech 101"
      url: "/tech101/"
      weight: 4
    - identifier: "cn-menu-separator-1"
      url: "#menu-separator"
      weight: 5
    - name: "摄影"
      url: "/photography/"
      weight: 6
    - name: "烹饪"
      url: "/cooking/"
      weight: 7
    - name: "摩托"
      url: "/motorcycle/"
      weight: 8
    - name: "关于"
      url: "/cn/about/"
      weight: 9
    - name: "简历"
      url: "/cn/resume/"
      weight: 10
  tech101:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "博客"
      url: "/cn/"
      weight: 2
    - name: "分类"
      url: "/categories/"
      weight: 3
    - name: "Tech 101"
      url: "/tech101/"
      weight: 4
    - identifier: "cn-menu-separator-1"
      url: "#menu-separator"
      weight: 5
    - name: "摄影"
      url: "/photography/"
      weight: 6
    - name: "烹饪"
      url: "/cooking/"
      weight: 7
    - name: "摩托"
      url: "/motorcycle/"
      weight: 8
    - name: "关于"
      url: "/cn/about/"
      weight: 9
    - name: "简历"
      url: "/cn/resume/"
      weight: 10
    - identifier: "cn-menu-separator-2"
      url: "#menu-separator"
      weight: 11

taxonomies:
  category: categories

params:
  description: "Leo Van's Personal Website | 范叶亮的个人网站"
  disqusURL: "https://leovan.me"
  licenseURL: "https://github.com/leovan/leovan.me/blob/master/LICENSE"
  googleAdsense: "ca-pub-2608165017777396"

  jsCookieVersion: "3.0.0"
  jsCookieCDN: "//cdnjs.cloudflare.com/ajax/libs"

  prismjsVersion: "1.26.0"
  prismjsCDN: "//cdnjs.cloudflare.com/ajax/libs"
  prismjsPlugin: ["show-language"]

  mathjaxVersion: "3.2.0"
  mathjaxCDN: "//cdnjs.cloudflare.com/ajax/libs"

  pseudocodeVersion: "latest"
  pseudocodeCDN: "//cdn.jsdelivr.net/npm"

  jQueryVersion: "3.6.0"
  jQueryCDN: "//cdnjs.cloudflare.com/ajax/libs"

  photoswipeVersion: "4.1.3"
  photoswipeCDN: "//cdnjs.cloudflare.com/ajax/libs"

  videojsVersion: "7.18.0"
  videojsCDN: "//cdnjs.cloudflare.com/ajax/libs"

  materialDesignWebFontVersion: "6.5.95"
  materialDesignWebFontCDN: "//cdnjs.cloudflare.com/ajax/libs"

  materialComponentsWebVersion: "latest"
  materialComponentsWebCDN: "//cdn.jsdelivr.net/npm"

  APlayerVersion: "1.10.1"
  APlayerCDN: "//cdnjs.cloudflare.com/ajax/libs"

  MetingJSVersion: "latest"
  MetingJSCDN: "//cdn.jsdelivr.net/npm"

  lazysizesVersion: "5.3.2"
  lazysizesCDN: "//cdnjs.cloudflare.com/ajax/libs"

  vanillaBackToTopVersion: "latest"
  vanillaBackToTopCDN: "//cdn.jsdelivr.net/npm"

  nanogallery2Version: "3.0.5"
  nanogallery2CDN: "//cdnjs.cloudflare.com/ajax/libs"

  lang:
    slogan:
      en: "Soldier to Soldier"
      cn: "手中有刀，心里有佛"
    author:
      en: "Leo Van"
      cn: "范叶亮"
    license:
      cn: "版权"
      en: "License"
    subscribe:
      cn: "订阅"
      en: "Subscribe"
    categories:
      cn: "分类"
      en: "Categories"
    tags:
      cn: "标签"
      en: "Tags"
    wordcount:
      cn: "字数"
      en: "Word Count"
    donate:
      cn: "赞 赏"
      en: "DONATE"
    donate_slogan:
      cn: "「真诚赞赏，手留余香」"
      en: "「Donation Given, Fragrance in Hand」"
    donate_2_cny:
      cn: "2 元"
      en: "2 CNY"
    donate_5_cny:
      cn: "5 元"
      en: "5 CNY"
    donate_10_cny:
      cn: "10 元"
      en: "10 CNY"
    donate_50_cny:
      cn: "50 元"
      en: "50 CNY"
    donate_100_cny:
      cn: "100 元"
      en: "100 CNY"
    donate_custom_cny:
      cn: "任意金额"
      en: "CUSTOM"

markup:
  defaultMarkdownHandler: blackfriday
  blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    hrefTargetBlank: true
    noreferrerLinks: true
    footnotereturnlinkcontents: "↩"
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
    parser:
      autoHeadingIDType: blackfriday
  tableOfContents:
    startLevel: 1
